name: Daily Blog Post

on:
  schedule:
    # Run every day at 10:00 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  create-blog-post:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pyautogui
          playwright install chromium
          
      - name: Create config file
        run: |
          echo '{
            "email": "${{ secrets.BLOG_EMAIL }}",
            "password": "${{ secrets.BLOG_PASSWORD }}"
          }' > config.json
          
      - name: Run blog automation
        run: python blog_automation.py --headless
        
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/
          retention-days: 7