name: Daily Tech Blog Post
on:
  schedule:
    # Run every day at 10:00 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  create-blog-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright google-generativeai python-dotenv pyautogui
          playwright install chromium

      - name: Configure environment
        env:
          BLOG_EMAIL: ${{ secrets.BLOG_EMAIL }}
          BLOG_PASSWORD: ${{ secrets.BLOG_PASSWORD }}
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
        run: |
          # Create necessary directories
          mkdir -p screenshots logs
          # Create config file
          echo '{
            "email": "${{ secrets.BLOG_EMAIL }}",
            "password": "${{ secrets.BLOG_PASSWORD }}",
            "google_ai": {
              "api_key": "${{ secrets.GOOGLE_AI_API_KEY }}"
            }
          }' > config.json
          
      - name: Run blog automation
        run: python blog_automation.py --headless
        
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: execution-artifacts
          path: |
            screenshots/
            logs/
          retention-days: 7
          
      - name: Upload analytics
        uses: actions/upload-artifact@v3
        with:
          name: analytics-data
          path: post_analytics.json
          retention-days: 30
          
      # Optional: Commit changes back to repository to keep history
      - name: Commit analytics data
        if: success()
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add post_analytics.json
          git commit -m "Update post analytics [skip ci]" || echo "No changes to commit"
          git push || echo "Nothing to push"